### ISSUE TITLE
Issue with script = soup.find_all("script", {"type": "text/javascript"})

### ISSUE THREAD

**Issue by mehdifekhar8** [cleitonleonel/pyquotex#14]
When ever this function is running i'm getting 
settings = script[1].get_text().strip().replace(";", "")
This is print of the script array 
[<script type="text/javascript">
    window.settings = {"fpjsDomain":null,"csrf":"d3sZkbB0EkSa571R31blhq7Kg8ToKfDhLt9E4cbw"};
</script>]
it only have one and no token 
Can anyone help me with this ?

**Comment by cleitonleonel** [comment]
> When ever this function is running i'm getting settings = script[1].get_text().strip().replace(";", "") This is print of the script array [<script type="text/javascript"> window.settings = {"fpjsDomain":null,"csrf":"d3sZkbB0EkSa571R31blhq7Kg8ToKfDhLt9E4cbw"}; </script>] it only have one and no token Can anyone help me with this ?

Your error is possibly related to the playwright's inability to log into your account, as this json response comes with your data when the login goes without problems and in your case it returns Null, which is basically a failed login.

**Comment by mehdifekhar8** [comment]
Thanks
