### ISSUE TITLE
Transformar em pacote instalável

### ISSUE THREAD

**Issue by iuriguilherme** [cleitonleonel/pyquotex#16]
Eu tinha feito um fork e transformado em pacote que dá pra instalar com o pip e importar em projetos existentes, mas eu teria que refazer este trabalho para a versão atual. Essa mudança geralmente não é intrusiva e o programa consegue funcionar como é agora, como pacote e como módulo concomitantemente, mas dependendo da estrutura do código, pode ser que tenha que mudar fundamentalmente pra manter a compatibilidade. Se eu fizer esse trabalho de novo, tu vai aceitar o pull request?

**Comment by cleitonleonel** [comment]
Envie o pull request.
