### ISSUE TITLE
Getting error while setup 

### ISSUE THREAD

**Issue by MuhammadUsamaMX** [cleitonleonel/pyquotex#17]
Getting error while running the script 
There is no module Myconnection

**Comment by cleitonleonel** [comment]
> Getting error while running the script There is no module Myconnection

![image](https://github.com/cleitonleonel/pyquotex/assets/11451914/91759d80-f9a0-4bec-b8f9-9916b8c29c81)
There really is no such module in this lib, I believe you are using another lib.

**Comment by MuhammadUsamaMX** [comment]
Ooo, actually I set up both Which may conflict 😕.
