### ISSUE TITLE
Erro Not_price

### ISSUE THREAD

**Issue by jhefreyads** [cleitonleonel/pyquotex#18]
sabe o que pode ser o erro not_price, quando vai realizar uma operação na corretora??

Websocket conectado com sucesso!!!
OK: Asset está aberto.
False not_price
Saldo corrente:  49435.6
Saindo...

**Comment by jhefreyads** [comment]
[Run.txt](https://github.com/cleitonleonel/pyquotex/files/15422220/Run.txt)

segue o modelo do meu codigo, estou fazendo testes ainda para integração em outro codigo. Mas travei nesse erro.

**Comment by cleitonleonel** [comment]
Não use vírgula e sim ponto.
Valores de moeda com vírgula (,) não funcionarão.

Em qui., 23 de mai. de 2024 17:16, jhefreyads ***@***.***>
escreveu:

**Comment by jhefreyads** [comment]
Mesmo com virgula está dando esse erro not_price, so não sei se tem a ver com o valor de entrada ou o preço atual da vela. Pelo tratamento do erro não estou conseguindo identificar.

**Comment by cleitonleonel** [comment]
> [Run.txt](https://github.com/cleitonleonel/pyquotex/files/15422220/Run.txt)
> 
> segue o modelo do meu codigo, estou fazendo testes ainda para integração em outro codigo. Mas travei nesse erro.
Pelo que percebi você usa:

`DEFAULT_AMOUNT = 50,0
DEFAULT_ASSET = "EURUSD (OTC)"
DEFAULT_DIRECTION = "PUT"
DEFAULT_DURATION = 60`

O erro ao que me parece pode ser `DEFAULT_ASSET = "EURUSD (OTC)"`

Deveria ser `DEFAULT_ASSET = "EURUSD_otc"`
