### ISSUE TITLE
Handshake status 403 Forbidden

### ISSUE THREAD

**Issue by masoud88** [cleitonleonel/pyquotex#20]
Hi I using your great API for a while , but recently I can't connect to qx .com and it said :
Handshake status 403 Forbidden -+-+-
There is any solution for this problem ?
Btw thanks for API it's really helping me

**Comment by cleitonleonel** [comment]
> Hi I using your great API for a while , but recently I can't connect to qx .com and it said : Handshake status 403 Forbidden -+-+- There is any solution for this problem ? Btw thanks for API it's really helping me

Thanks bro.
Check if recent updates resolve your issue.

**Comment by masoud88** [comment]
thanks for the update ,  but I got this error now :
`laywright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> C:\Users\mhfor\AppData\Local\ms-playwright\firefox-1425\firefox\firefox.exe -no-remote -headless -profile C:\Program Files (x86)\Google\Chrome\Application -juggler-pipe --disable-web-security --no-sandbox about:blank
<launched> pid=20816
[pid=20816][err] *** You are running in headless mode.
[pid=20816] <process did exit: exitCode=0, signal=null>
[pid=20816] starting temporary directories cleanup
=========================== logs ===========================
<launching> C:\Users\mhfor\AppData\Local\ms-playwright\firefox-1425\firefox\firefox.exe -no-remote -headless -profile C:\Program Files (x86)\Google\Chrome\Application -juggler-pipe --disable-web-security --no-sandbox about:blank
<launched> pid=20816
[pid=20816][err] *** You are running in headless mode.
[pid=20816] <process did exit: exitCode=0, signal=null>
[pid=20816] starting temporary directories cleanup
============================================================`

**Comment by cleitonleonel** [comment]
> thanks for the update , but I got this error now : `laywright._impl._api_types.Error: Browser closed. ==================== Browser output: ==================== <launching> C:\Users\mhfor\AppData\Local\ms-playwright\firefox-1425\firefox\firefox.exe -no-remote -headless -profile C:\Program Files (x86)\Google\Chrome\Application -juggler-pipe --disable-web-security --no-sandbox about:blank <launched> pid=20816 [pid=20816][err] *** You are running in headless mode. [pid=20816] <process did exit: exitCode=0, signal=null> [pid=20816] starting temporary directories cleanup =========================== logs =========================== <launching> C:\Users\mhfor\AppData\Local\ms-playwright\firefox-1425\firefox\firefox.exe -no-remote -headless -profile C:\Program Files (x86)\Google\Chrome\Application -juggler-pipe --disable-web-security --no-sandbox about:blank <launched> pid=20816 [pid=20816][err] *** You are running in headless mode. [pid=20816] <process did exit: exitCode=0, signal=null> [pid=20816] starting temporary directories cleanup ============================================================`

It seems to be something related to your browser, in this case Firefox and the playwright lib, it could be some version incompatibility, it's not very clear.
It appears that this is not an error related to quotex, but rather to the security settings of the browser in question.
It's up to you to identify the problem and try to solve it, obviously keep your record here, if you manage to solve it come back here and tell us how you solved it, this will help someone in the future.
