### ISSUE TITLE
pincode issue

### ISSUE THREAD

**Issue by David129676** [cleitonleonel/pyquotex#27]
Subject: Issue with quotexapi Login Process

Hello [Support Team],

I hope this message finds you well. I am encountering an issue with the quotexapi login process while integrating it into my trading bot.

Problem Description:

When attempting to log in using quotexapi, the API requires a PIN code during the login process. However, my current implementation of quotexapi does not seem to support handling this PIN code step automatically. As a result, the login process fails.

Steps Taken:

I have reviewed the API documentation provided by quotexapi to ensure correct usage and authentication methods.

I have checked for any updates or newer versions of quotexapi that might address issues related to handling PIN codes during login.

I have attempted to contact support through this communication for further assistance.

Additional Information:

My trading bot is programmed to automate trading activities based on data retrieved from quotexapi.
The bot successfully authenticates using email and password but fails when a PIN code is required during the login sequence.
Request:

Could you please provide guidance on how to handle the PIN code requirement using quotexapi? If there are specific API endpoints or methods that support this feature, I would greatly appreciate any documentation or examples that could assist in resolving this issue.

Thank you for your attention to this matter. I look forward to your prompt response and assistance.

Best regards,

**Comment by cleitonleonel** [comment]
```import os
from pathlib import Path
from quotexapi.stable_api import Quotex

email = "your email"
password = "password your email"
email_pass = "settings" # if uses 2FA and gmail account
user_data_dir = "user_data_dir"

client = Quotex(
    email=email,
    password=password,
    email_pass=email_pass,
    user_data_dir=Path(os.path.join(".", user_data_dir))
)
```

If your account use 2FA, and if you are using a Gmail account, then you must generate an app password so that the system can access your email and obtain the pincode.
https://support.google.com/accounts/answer/185833?hl=en

**Comment by David129676** [comment]
Autenticando usuário...
Login failed. E-mail ou senha inválidos
Login realizado com sucesso!!!
Connected: False
Saindo...
(.venv) PS C:\Users\hp\OneDrive\Desktop\project 2> 
i test manuly my gmail and password to login and thare are valid but system is not login  quotex and i genrate password to quotex i test pasword manuly but that also not solf my problem can you give any segation

**Comment by SantiiRepair** [comment]
> ```
> from pathlib import Path
> from quotexapi.stable_api import Quotex
> 
> email = "your email"
> password = "password your email"
> email_pass = "settings" # if uses 2FA and gmail account
> user_data_dir = "user_data_dir"
> 
> client = Quotex(
>     email=email,
>     password=password,
>     email_pass=email_pass,
>     user_data_dir=Path(os.path.join(".", user_data_dir))
> )
> ```
> 
> If your account use 2FA, and if you are using a Gmail account, then you must generate an app password so that the system can access your email and obtain the pincode. https://support.google.com/accounts/answer/185833?hl=en

Olha [aqui](https://github.com/SantiiRepair/quotexpy/blob/cc0a88c3c8afe7d8372830e7c4d3f2a6c5b850b7/quotexpy/http/login.py#L23)

**Comment by cleitonleonel** [comment]
> > ```
> > from pathlib import Path
> > from quotexapi.stable_api import Quotex
> > 
> > email = "your email"
> > password = "password your email"
> > email_pass = "settings" # if uses 2FA and gmail account
> > user_data_dir = "user_data_dir"
> > 
> > client = Quotex(
> >     email=email,
> >     password=password,
> >     email_pass=email_pass,
> >     user_data_dir=Path(os.path.join(".", user_data_dir))
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If your account use 2FA, and if you are using a Gmail account, then you must generate an app password so that the system can access your email and obtain the pincode. https://support.google.com/accounts/answer/185833?hl=en
> 
> Olha [aqui](https://github.com/SantiiRepair/quotexpy/blob/cc0a88c3c8afe7d8372830e7c4d3f2a6c5b850b7/quotexpy/http/login.py#L23)

Sim, o sistema já possui isso. Difere um pouco do que vocês fizeram.
Na PyQuotex isso é automatizado, mas também existe o modo manual, basta passar None como valor para a email_pass=None, teoricamente funciona kkkk.

**Comment by SantiiRepair** [comment]
ta bom mano
