### ISSUE TITLE
Observaciones relacionadas al inicio de sesión

### ISSUE THREAD

**Issue by rloverab** [cleitonleonel/pyquotex#28]
Saludos.

No he podido realizar un inicio de sesión exitoso desde hace un tiempo. Se dice que cloudflare identifica la API como riesgosa y la bloquea.

He realizado pruebas y he notado que el problema no parece ser tanto de la API sino la versión de Firefox de Playwright. 

He visto el proceso de inicio de sesión y consiste en tomar los datos del usuario para llenar de forma automática el formulario de inicio de sesión tal y como lo haría un usuario de manera manual, tomado el correo electrónico y la contraseña y pegándolo en los textbox correspondientes.

Pude iniciar sesión manualmente (como si quisiera operar sin el bot) usando las versiones regulares de Firefox y Google Chrome instalados en mi equipo. También hice una prueba usando una versión Nightly de Firefox obtenido desde el sitio oficial y pude ingresar satisfactoriamente. Sin embargo, al intentar hacer esto mismo usando la versión de Firefox de Playwright ha sido imposible. Por curiosidad, probé hacerlo en las versiones de Playwright de Chromium y WebKit pero igualmente sin éxito.

Me queda claro que el problema no es la API sino navegador utilizado para obtener los datos de la sesión.

Para abrirlos navegadores Playwright deben usar los siguientes comandos desde la terminal:

- Firefox: **playwright ff**
- Chromium: **playwright cr**
- WebKit: **playwright wk**

**Comment by cleitonleonel** [comment]
> Saudações.
> 
> Não foi possível realizar um início de sessão exitoso desde há um tempo. Se você disser que o Cloudflare identifica a API como perigosa e bloqueada.
> 
> Ele realizou testes e notou que o problema não parece ser tanto na API como na versão do Firefox do Playwright.
> 
> Ele viu o processo de início de sessão e consistiu em tomar os dados do usuário para preencher o formulário automaticamente o formulário de início de sessão, assim como ele teria um manual de usuário, tomou o correio eletrônico e a senha e pegá-lo na caixa de texto correspondentes.
> 
> Você pode iniciar a sessão manualmente (como se deseja operar sem o bot) usando as versões normais do Firefox e do Google Chrome instaladas em meu equipamento. Também fiz um teste usando uma versão Nightly do Firefox obtida no site oficial e pude entrar satisfatoriamente. No entanto, tentar fazer isso mesmo usando a versão do Firefox do Playwright foi impossível. Por curiosidade, tentei fazer isso nas versões do Playwright de Chromium e WebKit, mas igualmente sem sucesso.
> 
> Fiquei claro que o problema não é a API do navegador usada para obter os dados da sessão.
> 
> Para abrir os navegadores, o Playwright deve usar os seguintes comandos do terminal:
> 
> * Firefox: **dramaturgo ff**
> * Chromium: **dramaturgo cr**
> * WebKit: **dramaturgo wk**

Estoy trabajando en una actualización para usar selenio, no era lo que quería, pero por ahora es lo que parece funcionar.

**Comment by rloverab** [comment]
> > Saudações.
> > Não foi possível realizar um início de sessão exitoso desde há um tempo. Se você disser que o Cloudflare identifica a API como perigosa e bloqueada.
> > Ele realizou testes e notou que o problema não parece ser tanto na API como na versão do Firefox do Playwright.
> > Ele viu o processo de início de sessão e consistiu em tomar os dados do usuário para preencher o formulário automaticamente o formulário de início de sessão, assim como ele teria um manual de usuário, tomou o correio eletrônico e a senha e pegá-lo na caixa de texto correspondentes.
> > Você pode iniciar a sessão manualmente (como se deseja operar sem o bot) usando as versões normais do Firefox e do Google Chrome instaladas em meu equipamento. Também fiz um teste usando uma versão Nightly do Firefox obtida no site oficial e pude entrar satisfatoriamente. No entanto, tentar fazer isso mesmo usando a versão do Firefox do Playwright foi impossível. Por curiosidade, tentei fazer isso nas versões do Playwright de Chromium e WebKit, mas igualmente sem sucesso.
> > Fiquei claro que o problema não é a API do navegador usada para obter os dados da sessão.
> > Para abrir os navegadores, o Playwright deve usar os seguintes comandos do terminal:
> > 
> > * Firefox: **dramaturgo ff**
> > * Chromium: **dramaturgo cr**
> > * WebKit: **dramaturgo wk**
> 
> Estoy trabajando en una actualización para usar selenio, no era lo que quería, pero por ahora es lo que parece funcionar.

Estuve haciendo pruebas y note que el problema esta en la version del Firefox.

Cuando instalo el playwright usando **pip install playwright** se instala la ultima version (1.45.1). Esta version instala la version 127.0 de firefox.

Probé instalando la version 1.44.0 de playwright usando **pip install playwright==1.44.0** el cual instala la version 125.0 de firefox. Esta no me da problemas de inicio de sesión.
