### ISSUE TITLE
Api não conecta na conta REAL

### ISSUE THREAD

**Issue by lukefeix** [cleitonleonel/pyquotex#29]
Bom dia amigo, só para dar um feedback.
A api não conecta na conta real pois a função change_account só modifica a variavel dentro do stable_api.py.. precisa ser modificado de forma global na variavel self.api.account_type..

Fazendo essa modificação,  ele vai retornar o saldo da conta real certinho. abre operação, mas a função de checkwin não consegue encontrar o id da operação. Não investiguei mais a fundo, o problema pode ser no envio do json da função BUY, ou só no retorno do websocket para encontrar o id da operação.

**Comment by lukefeix** [comment]
Descobri, depois de umas 20 entradas tentando achar o problema kkk.
Além daquele ajuste da variavel dentro da API, ao mudar a conta para real ou demo, deve ser enviado para o websocket a mensagem: 42["account/change",{"demo":0,"tournamentId":0}]

Fazendo isso, ele retorna certinho o id de compra

**Comment by cleitonleonel** [comment]
> Descobri, depois de umas 20 entradas tentando achar o problema kkk. Além daquele ajuste da variavel dentro da API, ao mudar a conta para real ou demo, deve ser enviado para o websocket a mensagem: 42["account/change",{"demo":0,"tournamentId":0}]
> 
> Fazendo isso, ele retorna certinho o id de compra

Exatamente, isso foi alterado recentemente na quotex, antes se iniciasse com um tipo de conta poderia alterar apenas enviando novamente o tipo de conta no envio da ordem, mas agora é necessário enviar um comando ao websocket sinalizando a alteração do tipo de conta.
