### ISSUE TITLE
problema ao utilizar a aplicação

### ISSUE THREAD

**Issue by aurorafontana** [cleitonleonel/pyquotex#31]
<img width="1229" alt="Screenshot 2024-08-13 alle 11 44 09" src="https://github.com/user-attachments/assets/5154ffd0-b4e5-4151-a0f3-e6d47eb0d840">

Olá,

Estou enfrentando um problema ao utilizar a aplicação. Segui todos os passos e consegui iniciar o processo automático através do navegador. A autenticação ocorre com sucesso, o processo continua, o navegador é fechado automaticamente e, a partir daí, não consigo mais prosseguir.

Agora, toda vez que tento reabrir o app, aparece a seguinte mensagem:

arduino
Copia codice
Login failed, but continuing...

██████╗ ██╗   ██╗ ██████╗ ██╗   ██╗ ██████╗ ████████╗███████╗██╗  ██╗
██╔══██╗╚██╗ ██╔╝██╔═══██╗██║   ██║██╔═══██╗╚══██╔══╝██╔════╝╚██╗██╔╝
██████╔╝ ╚████╔╝ ██║   ██║██║   ██║██║   ██║   ██║   █████╗   ╚███╔╝ 
██╔═══╝   ╚██╔╝  ██║▄▄ ██║██║   ██║██║   ██║   ██║   ██╔══╝   ██╔██╗ 
██║        ██║   ╚██████╔╝╚██████╔╝╚██████╔╝   ██║   ███████╗██╔╝ ██╗
╚═╝        ╚═╝    ╚══▀▀═╝  ╚═════╝  ╚═════╝    ╚═╝   ╚══════╝╚═╝  ╚═╝

{'symbol_id': 67, 'time': 1723540200, 'open': 0.90401, 'close': 0.90413, 'high': 0.90422, 'low': 0.90377, 'ticks': 76, 'last_tick': 1723540259.602, 'asset': 'AUDCAD_otc'}
...

Saindo...
Parece que ele tenta continuar o processo mesmo após falhar no login, mas apenas lista os valores das moedas e depois fecha o programa automaticamente. Já tentei reconfigurar e reiniciar, mas o problema persiste.

Poderiam me ajudar a entender o que está acontecendo e como posso resolver esse problema?

Agradeço desde já pelo suporte!

**Comment by cleitonleonel** [comment]
> <img alt="Screenshot 2024-08-13 alle 11 44 09" width="1229" src="https://private-user-images.githubusercontent.com/52195369/357361091-5154ffd0-b4e5-4151-a0f3-e6d47eb0d840.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDYzNjUsIm5iZiI6MTcyMzU0NjA2NSwicGF0aCI6Ii81MjE5NTM2OS8zNTczNjEwOTEtNTE1NGZmZDAtYjRlNS00MTUxLWEwZjMtZTZkNDdlYjBkODQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwNDc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkZjcxZmVlNGIyMjNjYTFkOTI4ZDc0MWFjNWFlZGU0YjBlOTM0ZmVjZTllYWYwZjRmZTcyMWQ2MmRlOGY2MTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LLD5wJD5Ef4EmO4Hswo-69NQTIOmZsd8ATmAffq_52g">
> Olá,
> 
> Estou enfrentando um problema ao utilizar a aplicação. Segui todos os passos e consegui iniciar o processo automático através do navegador. A autenticação ocorre com sucesso, o processo continua, o navegador é fechado automaticamente e, a partir daí, não consigo mais prosseguir.
> 
> Agora, toda vez que tento reabrir o app, aparece a seguinte mensagem:
> 
> arduino Copia codice Login failed, but continuing...
> 
> ██████╗ ██╗ ██╗ ██████╗ ██╗ ██╗ ██████╗ ████████╗███████╗██╗ ██╗ ██╔══██╗╚██╗ ██╔╝██╔═══██╗██║ ██║██╔═══██╗╚══██╔══╝██╔════╝╚██╗██╔╝ ██████╔╝ ╚████╔╝ ██║ ██║██║ ██║██║ ██║ ██║ █████╗ ╚███╔╝ ██╔═══╝ ╚██╔╝ ██║▄▄ ██║██║ ██║██║ ██║ ██║ ██╔══╝ ██╔██╗ ██║ ██║ ╚██████╔╝╚██████╔╝╚██████╔╝ ██║ ███████╗██╔╝ ██╗ ╚═╝ ╚═╝ ╚══▀▀═╝ ╚═════╝ ╚═════╝ ╚═╝ ╚══════╝╚═╝ ╚═╝
> 
> {'symbol_id': 67, 'time': 1723540200, 'open': 0.90401, 'close': 0.90413, 'high': 0.90422, 'low': 0.90377, 'ticks': 76, 'last_tick': 1723540259.602, 'asset': 'AUDCAD_otc'} ...
> 
> Saindo... Parece que ele tenta continuar o processo mesmo após falhar no login, mas apenas lista os valores das moedas e depois fecha o programa automaticamente. Já tentei reconfigurar e reiniciar, mas o problema persiste.
> 
> Poderiam me ajudar a entender o que está acontecendo e como posso resolver esse problema?
> 
> Agradeço desde já pelo suporte!

Qual código você executa para receber isso?

me parece o comportamento normal dos exemplos fornecidos no readme, mais especificamente a função get_candles.

**Comment by aurorafontana** [comment]
Para receber essa mensagem, envio o comando: python3 app.py. Talvez eu não tenha entendido o passo seguinte. Então, configurei a visibilidade como false para visualizar o navegador e inserir o código solicitado, que é enviado por e-mail, caso contrário, o acesso não acontece. Uma vez aberto o navegador, após alguns segundos ele se fecha, os valores são mostrados e eu não entendi como devo prosseguir, já que o navegador não abre mais para ver a plataforma.

Não entendi como prosseguir. Poderiam me orientar sobre o que devo fazer para continuar?

Obrigado!

**Comment by cleitonleonel** [comment]
> Para receber essa mensagem, envio o comando: python3 app.py. Talvez eu não tenha entendido o passo seguinte. Então, configurei a visibilidade como false para visualizar o navegador e inserir o código solicitado, que é enviado por e-mail, caso contrário, o acesso não acontece. Uma vez aberto o navegador, após alguns segundos ele se fecha, os valores são mostrados e eu não entendi como devo prosseguir, já que o navegador não abre mais para ver a plataforma.
> 
> Não entendi como prosseguir. Poderiam me orientar sobre o que devo fazer para continuar?
> 
> Obrigado!

O arquivo app.py é apenas um conjunto de exemplos do que esta biblioteca tem a oferecer. O que você esperava que acontecesse?

**Comment by aurorafontana** [comment]
Estou anexando uma captura de tela com uma Gift para mostrar o que aparece agora. Por exemplo, ele me dá esses dados talvez porque eu já esteja logado, mas não abre o navegador. Por isso, não entendo se preciso iniciar outro script ou se isso funciona como um bot automático. Não consigo entender como testar, conforme mostrado no vídeo de apresentação.

Url: https://clickio.gyazo.com/1fb40f71412a426c8a97585749ca37fa

**Comment by cleitonleonel** [comment]
> Estou anexando uma captura de tela com uma Gift para mostrar o que aparece agora. Por exemplo, ele me dá esses dados talvez porque eu já esteja logado, mas não abre o navegador. Por isso, não entendo se preciso iniciar outro script ou se isso funciona como um bot automático. Não consigo entender como testar, conforme mostrado no vídeo de apresentação.
> 
> Url: https://clickio.gyazo.com/1fb40f71412a426c8a97585749ca37fa

O navegador só será usado para autenticação, após gerar o jason com os dados da sessão ele não será mais utilizado até que sua sessão expire.
Quanto ao funcionamento, você está confundindo o propósito dos exemplos, aí no arquivo app.py tem os métodos base para você desenvolver um bot automático a sua maneira, mas ele por si só não é um bot automático.
Você precisa sim desenvolver com base nesses exemplos, um outro código com sua lógica.

**Comment by aurorafontana** [comment]
Sim, entendo que preciso utilizar uma estratégia, com certeza. O que não entendi é como configurar ou associar uma estratégia ao projeto que você desenvolveu. Como posso implementar e testar uma estratégia automática, seja para abertura, fechamento, ou qualquer outra? Poderia me orientar sobre como fazer isso?

**Comment by cleitonleonel** [comment]
> Sim, entendo que preciso utilizar uma estratégia, com certeza. O que não entendi é como configurar ou associar uma estratégia ao projeto que você desenvolveu. Como posso implementar e testar uma estratégia automática, seja para abertura, fechamento, ou qualquer outra? Poderia me orientar sobre como fazer isso?

Todos os métodos que precisa para criar sua automação estão dispostos no arquivo app.py basta você desenvolver uma lógica para sua regra de negócios e implementar isso.
Tem lá o método de autenticação, de obter velas, de abertura e fechamento de ordens, tem método que aguarda o fechamento, tem método de venda, obter saldo demo e real, método para alternar entre as contas demo e real.
Use como exemplos de uso os vários bots e automações existentes no github que fazem uso da lib iqoption, essa lib segue um design parecido, embora use métodos assíncronos a ideia é a mesma.

**Comment by aurorafontana** [comment]
Última pergunta, acho que estou começando a entender. Eu devo inserir o script dentro do arquivo app.py? Devo colocar a estratégia automática dentro dele para criar um bot? Dessa forma, ele se autentica e procede automaticamente com o trabalho automatizado?

**Comment by cleitonleonel** [comment]
> Última pergunta, acho que estou começando a entender. Eu devo inserir o script dentro do arquivo app.py? Devo colocar a estratégia automática dentro dele para criar um bot? Dessa forma, ele se autentica e procede automaticamente com o trabalho automatizado?

Quase isso, como eu disse você precisa desenvolver um novo código, o arquivo app.py está ali apenas para mostrar como funciona a chamada dos métodos da lib.Veja como foi implementado o método de login no arquivo app.py e faça o mesmo em um outro arquivo, siga fazendo seu código e implementando nele os métodos contidos no arquivo app.py a medida que for avançando no desenvolvimento do seu código.
