### ISSUE TITLE
Faltando arquivo processor.py

### ISSUE THREAD

**Issue by msgprado** [cleitonleonel/pyquotex#36]
`from quotexapi.utils.processor import process_candles, get_color`  

Import "quotexapi.utils.processor" could not be resolved

**Comment by cleitonleonel** [comment]
> `from quotexapi.utils.processor import process_candles, get_color`
> 
> Import "quotexapi.utils.processor" could not be resolved

https://github.com/cleitonleonel/pyquotex/commit/2b5dfcc9f2d22b7f2181a3930b4c9edf74bdec18
