### ISSUE TITLE
XULRunner

### ISSUE THREAD

**Issue by BaranetharanS** [cleitonleonel/pyquotex#37]
I am getting error:

![Screenshot 2024-11-02 212319](https://github.com/user-attachments/assets/1fa358a8-1f9c-48ca-896b-47641dc4137f)

and when given OK. then>
"
Traceback (most recent call last):
  File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\app.py", line 518, in <module>
    loop.run_until_complete(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\app.py", line 507, in main
    await buy_simple()
  File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\app.py", line 120, in buy_simple
    check_connect, message = await client.connect()
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\quotexapi\stable_api.py", line 217, in connect
    check, reason = await self.api.connect(self.account_is_demo)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\quotexapi\api.py", line 393, in connect
    check_websocket, websocket_reason = await self.start_websocket()
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\quotexapi\api.py", line 336, in start_websocket
    await self.authenticate()
  File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\quotexapi\api.py", line 319, in authenticate
    status, message = await self.login(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\quotexapi\http\login.py", line 19, in __call__
    return await self.get_cookies_and_ssid()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\quotexapi\http\qxbroker.py", line 168, in get_cookies_and_ssid
    await self.main()
  File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\quotexapi\http\qxbroker.py", line 165, in main
    await self.run(playwright)
  File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\quotexapi\http\qxbroker.py", line 77, in run
    context = await browser.launch_persistent_context(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\playwright\async_api\_generated.py", line 14217, in launch_persistent_context
    await self._impl_obj.launch_persistent_context(
  File "C:\Users\baran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\playwright\_impl\_browser_type.py", line 157, in launch_persistent_context
    from_channel(await self._channel.send("launchPersistentContext", params)),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\baran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\playwright\_impl\_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: BrowserType.launch_persistent_context: Timeout 180000ms exceeded.
Call log:
<launching> C:\Users\baran\AppData\Local\ms-playwright\firefox-1449\firefox\firefox.exe -no-remote -headless -profile browser -juggler-pipe --disable-web-security --no-sandbox --aggressive-cache-discard --disable-cache --disable-application-cache --disable-offline-load-stale-cache --disk-cache-size=0 --disable-background-networking --disable-default-apps --disable-extensions --disable-sync --disable-translate --hide-scrollbars --metrics-recording-only --mute-audio --safebrowsing-disable-auto-update --ignore-certificate-errors --ignore-ssl-errors --ignore-certificate-errors-spki-list --disable-features=LeakyPeeker --disable-setuid-sandbox about:blank
  - <launched> pid=2616
  - [pid=2616][err] *** You are running in headless mode."
  
  
  I am running on 
  ASUS Nitro AN515-54
 
 
 THANKS

**Comment by cleitonleonel** [comment]
> Traceback (most recent call last): File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\app.py", line 518, in loop.run_until_complete(main()) File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 687, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\app.py", line 507, in main await buy_simple() File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\app.py", line 120, in buy_simple check_connect, message = await client.connect() ^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\quotexapi\stable_api.py", line 217, in connect check, reason = await self.api.connect(self.account_is_demo) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\quotexapi\api.py", line 393, in connect check_websocket, websocket_reason = await self.start_websocket() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\quotexapi\api.py", line 336, in start_websocket await self.authenticate() File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\quotexapi\api.py", line 319, in authenticate status, message = await self.login( ^^^^^^^^^^^^^^^^^ File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\quotexapi\http\login.py", line 19, in **call** return await self.get_cookies_and_ssid() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\quotexapi\http\qxbroker.py", line 168, in get_cookies_and_ssid await self.main() File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\quotexapi\http\qxbroker.py", line 165, in main await self.run(playwright) File "C:\Users\baran\OneDrive\Desktop\pyquotex-master\quotexapi\http\qxbroker.py", line 77, in run context = await browser.launch_persistent_context( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\baran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\playwright\async_api_generated.py", line 14217, in launch_persistent_context await self._impl_obj.launch_persistent_context( File "C:\Users\baran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\playwright_impl_browser_type.py", line 157, in launch_persistent_context from_channel(await self._channel.send("launchPersistentContext", params)), ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\baran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\playwright_impl_connection.py", line 59, in send return await self._connection.wrap_api_call( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\baran\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\playwright_impl_connection.py", line 514, in wrap_api_call raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None playwright._impl._errors.TimeoutError: BrowserType.launch_persistent_context: Timeout 180000ms exceeded. Call log: C:\Users\baran\AppData\Local\ms-playwright\firefox-1449\firefox\firefox.exe -no-remote -headless -profile browser -juggler-pipe --disable-web-security --no-sandbox --aggressive-cache-discard --disable-cache --disable-application-cache --disable-offline-load-stale-cache --disk-cache-size=0 --disable-background-networking --disable-default-apps --disable-extensions --disable-sync --disable-translate --hide-scrollbars --metrics-recording-only --mute-audio --safebrowsing-disable-auto-update --ignore-certificate-errors --ignore-ssl-errors --ignore-certificate-errors-spki-list --disable-features=LeakyPeeker --disable-setuid-sandbox about:blank
> 
> * pid=2616
> * [pid=2616][err] *** You are running in headless mode."

This has no direct relation to the lib, the errors are from your playwright's installation, I suggest reviewing the installation of this tool before trying any other action.
https://playwright.dev/docs/intro#installing-playwright

**Comment by BaranetharanS** [comment]
I tried all the above action, but the same error with is coming with firefox & playwright. 
is there any method to change the playwright to any other lib?

**Comment by cleitonleonel** [comment]
> I tried all the above action, but the same error with is coming with firefox & playwright. 
> is there any method to change the playwright to any other lib?
> 

How is your configuration file? Your config.ini.

**Comment by BaranetharanS** [comment]
here it is, is it correct?

config.ini

[settings]
email=baranetharan@gmail.com
password=**********
email_pass=***********
user_data_dir=C:\Program Files\Mozilla Firefox\firefox.exe

**Comment by cleitonleonel** [comment]
> user_data_dir=C:\Program Files\Mozilla Firefox\firefox.exe

This is your error, this field is not the path of the executable file but a path to create your user profile, any path of your choice to create the browser instance, just say in which folder you want to save the data.
Exemplo:
user_data_dir=C:\Users\baran\OneDrive\Desktop\pyquotex-master\profile

**Comment by BaranetharanS** [comment]
I have changed it to the path to which you have provided, but I am still getting the same error

**Comment by cleitonleonel** [comment]
> I have changed it to the path to which you have provided, but I am still getting the same error

run pip uninstall -r requirements.txt and pip installl -r requirements.txt

**Comment by BaranetharanS** [comment]
"pip uninstall -r requirements.txt

restart

pip install -r requirements.txt

restart

python -m playwright install firefox"

again same error.

**Comment by cleitonleonel** [comment]
> "pip uninstall -r requirements.txt
> 
> restart
> 
> pip install -r requirements.txt
> 
> restart
> 
> python -m playwright install firefox"
> 
> again same error.

Ok friend, so your problem can't be solved here, take a look at the playwright's repository and see if you can get help.

**Comment by BaranetharanS** [comment]
IT'S WORKIING AFTER I MOVED EVERYTHING AWAY FROM ONEDRIVE.
