### ISSUE TITLE
esta funcionando esta api?

### ISSUE THREAD

**Issue by leoteixeira2016** [cleitonleonel/pyquotex#4]
ao inserir email e senha diz estar conectado e nao segue com o codigo.
![image](https://github.com/cleitonleonel/pyquotex/assets/21205597/e9eab82e-be07-4eac-a9cb-bdeb23d912aa)

**Comment by cleitonleonel** [comment]
> ao inserir email e senha diz estar conectado e nao segue com o codigo. ![image](https://user-images.githubusercontent.com/21205597/241800493-e9eab82e-be07-4eac-a9cb-bdeb23d912aa.png)

![image](https://github.com/cleitonleonel/pyquotex/assets/11451914/06344e88-3bc6-42fc-9aca-acab7ab27005)
