### ISSUE TITLE
funcion get_candle() limitada???

### ISSUE THREAD

**Issue by nsivov21** [cleitonleonel/pyquotex#5]
Queria consultar un problema que tengo con la API, al momento de solicitar las última hora de informacion de un asset, la api me carga correctamente la informacion y puedo hacer la conversion para tener las velas de la última hora, pero al momento de solicitar datos de mas de 1 hora (3600 segundos), si bien carga la información en cada minuto, solamente me da el valor open, no tengo como obtener el resto de los datos (close, high, low) y por lo tanto no puedo realizar ningun analisis cuando necesito obtener datos de más de una hora...

   
![60 minutes](https://github.com/cleitonleonel/pyquotex/assets/84388842/2d3eb890-53f6-4055-8363-5d4951466687)

Aqui el resultado pidiendo 3600 segundos

![120 minutos](https://github.com/cleitonleonel/pyquotex/assets/84388842/0c1c15a1-d781-44e6-bcaa-50ef1b273a5d)

Aqui el resultado solo cambiando en vez de pedir 3600 segundos, pidiendo 7200 segundos

Saludos

**Comment by nsivov21** [comment]
para mostrar directamente sin procesar la informacion, aca dejo la data obtenida cuando pido datos de 1 hora vs datos de 2 horas, cuando pido 1 hora, trae todos los ticks y los separa en ms, mientras que al pedir 2 horas, solo trae el tick open y sin ms para procesar

![60 min audusd](https://github.com/cleitonleonel/pyquotex/assets/84388842/7d220487-b649-434d-97e9-140e04388d95)

1 hora de AUDUSD_otc


![120 min audusd](https://github.com/cleitonleonel/pyquotex/assets/84388842/1bec8b12-d931-4907-98bf-761cb4e8e500)

2 horas de AUDUSD_otc

**Comment by cleitonleonel** [comment]
> Queria consultar un problema que tengo con la API, al momento de solicitar las última hora de informacion de un asset, la api me carga correctamente la informacion y puedo hacer la conversion para tener las velas de la última hora, pero al momento de solicitar datos de mas de 1 hora (3600 segundos), si bien carga la información en cada minuto, solamente me da el valor open, no tengo como obtener el resto de los datos (close, high, low) y por lo tanto no puedo realizar ningun analisis cuando necesito obtener datos de más de una hora...
> 
> ![60 minutes](https://user-images.githubusercontent.com/84388842/244880675-2d3eb890-53f6-4055-8363-5d4951466687.png)
> 
> Aqui el resultado pidiendo 3600 segundos
> 
> ![120 minutos](https://user-images.githubusercontent.com/84388842/244880763-0c1c15a1-d781-44e6-bcaa-50ef1b273a5d.png)
> 
> Aqui el resultado solo cambiando en vez de pedir 3600 segundos, pidiendo 7200 segundos
> 
> Saludos

De acuerdo, analizaré esto, hice la API basada en la documentación de la versión de Anson https://lu-yi-hsun.github.io/quotexapi/ y recogí algunas partes en común con la lib para iqoption que es también suyo... por lo que podría haber errores y limitaciones.

**Comment by nsivov21** [comment]
> De acuerdo, analizaré esto, hice la API basada en la documentación de la versión de Anson https://lu-yi-hsun.github.io/quotexapi/ y recogí algunas partes en común con la lib para iqoption que es también suyo... por lo que podría haber errores y limitaciones.

Algo que estoy evaluando es que la API de Quoex trae los datos en ticks, no creando directamente la vela, cosa que en la API de iqoption si trabaja de esa manera... sigo evaluando y tratando de ver si a traves de un scrape puedo obligar a seleccionar la vela en vez de ticks que es el grafico por defecto, pero hasta el momento no he podido encontrarle una solución, por lo que hacer análisis de rsi o medias móviles es prácticamente imposible...

Saludos!!!
