### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by fematossilva** [cleitonleonel/pyquotex#6]
Estou tendo o seguinte erro ao executar o código, alguém sabe como resolver?

Autenticando usuário...
Traceback (most recent call last):
  File "C:\Felipe\bot_undetected\main.py", line 176, in <module>
    get_balance()
  File "C:\Felipe\bot_undetected\main.py", line 35, in get_balance
    check_connect, message = login()
  File "C:\Felipe\bot_undetected\main.py", line 11, in login
    check, reason = client.connect()
  File "C:\Felipe\bot_undetected\quotexapi\stable_api.py", line 142, in connect
    check, reason = self.api.connect()
  File "C:\Felipe\bot_undetected\quotexapi\api.py", line 262, in connect
    ssid, self.cookies = self.get_ssid()
  File "C:\Felipe\bot_undetected\quotexapi\api.py", line 198, in get_ssid
    ssid, cookies = self.login(
  File "C:\Felipe\bot_undetected\quotexapi\http\login.py", line 86, in __call__
    "_token": self.get_token(),
  File "C:\Felipe\bot_undetected\quotexapi\http\login.py", line 29, in get_token
    return self.get_soup().find(
TypeError: 'NoneType' object is not subscriptable

**Comment by cleitonleonel** [comment]
> Estou tendo o seguinte erro ao executar o código, alguém sabe como resolver?
> 
> Autenticando usuário... Traceback (most recent call last): File "C:\Felipe\bot_undetected\main.py", line 176, in get_balance() File "C:\Felipe\bot_undetected\main.py", line 35, in get_balance check_connect, message = login() File "C:\Felipe\bot_undetected\main.py", line 11, in login check, reason = client.connect() File "C:\Felipe\bot_undetected\quotexapi\stable_api.py", line 142, in connect check, reason = self.api.connect() File "C:\Felipe\bot_undetected\quotexapi\api.py", line 262, in connect ssid, self.cookies = self.get_ssid() File "C:\Felipe\bot_undetected\quotexapi\api.py", line 198, in get_ssid ssid, cookies = self.login( File "C:\Felipe\bot_undetected\quotexapi\http\login.py", line 86, in **call** "_token": self.get_token(), File "C:\Felipe\bot_undetected\quotexapi\http\login.py", line 29, in get_token return self.get_soup().find( TypeError: 'NoneType' object is not subscriptable

Esse erro se dá pelo fato de que a quotex está bloqueando quaisquer conexões automatizadas que não renderizem o javascript da página, na verdade é um bloqueio por parte da cloudflare, agora só usando um browser automatizado como selenium ou playwright, por sorte já implementei isso no sistema e basta ativar com browser=True `# browser=True enable playwright
client = Quotex(email="example@gmail.com", password="password", browser=True)` 
Ainda farei uma atualização no código pra que isso seja padrão, pois não creio que voltará a funcionar apenas com requests e urllib .

**Comment by fematossilva** [comment]
> 

Muito obrigado, sou iniciante e me ajudou muito. Muito obrigado mais uma vez!
