### ISSUE TITLE
get_candle não está funcionando

### ISSUE THREAD

**Issue by dougrn** [cleitonleonel/pyquotex#7]
Usava a função normalmente até alguns dias atrás e simplesmente não funciona mais.
Houve alguma mudança?

**Comment by cleitonleonel** [comment]
A plataforma fez alterações na parte de autenticação, antes a conexão era feita de forma simplificada e sem tantos bloqueios, mas como era de se esperar sempre irão bloquear acesso indevido, e a dica é:
Sempre que houver a quebra de alguma funcionalidade então a alteração é na plataforma e não a biblioteca, obviamente se não houverem mudanças recentes no histórico do repositório claro.

**Comment by dougrn** [comment]
Conseguimos resolver?

**Comment by cleitonleonel** [comment]
> Conseguimos resolver?

Me diz você, acha que consegue resolver ???
No momento estou bem atolado de serviços e sem muito tempo livre para quaisquer correções, a propósito o repositório é público exatamente para que outros devs contribuam com algum código, caso esse tenha alguma solução aí, faça um pull request e ajude a manter o projeto, desde já agradeço...

**Comment by dougrn** [comment]
Vish, eu bati cabeça aqui e não teve jeito....

**Comment by cleitonleonel** [comment]
> Vish, eu bati cabeça aqui e não teve jeito....
Parece clichê, mas aqui funciona no linux ubuntu 22.04

**Comment by dougrn** [comment]
vou tentar criar uma vps na amazon entao... vamos ver
