### ISSUE TITLE
How do I fix this error

### ISSUE THREAD

**Issue by SooDa3277** [cleitonleonel/pyquotex#8]
File "d:\New folder (2)\pyquotex-master\quotexapi\ws\client.py", line 29, in __init__
    websocket.enableTrace(self.api.trace_ws)
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'websocket' has no attribute 'enableTrace

**Comment by alrtor** [comment]
pip3 uninstall websocket
pip3 uninstall websocket-client
pip3 install websocket-client

**Comment by alrtor** [comment]
pip uninstall websocket
pip uninstall websocket-client
pip install websocket-client

**Comment by cleitonleonel** [comment]
> websocket

pip uninstall websocket
pip uninstall websocket-client
pip install websocket-client
